#string validatos challange
s = input()
b = list(filter(lambda i: str(i).isalnum(),s))
print(len(b)>0)
b = list(filter(lambda i: str(i).isalpha(),s))
print(len(b)>0)
b = list(filter(lambda i: str(i).isdigit(),s))
print(len(b)>0)
b = list(filter(lambda i: str(i).islower(),s))
print(len(b)>0)
b = list(filter(lambda i: str(i).isupper(),s))
print(len(b)>0)